timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
  requestedVerifyOption: VERIFIED
  machineType: E2_HIGHCPU_8
substitutions:
  _IMAGE: europe-west1-docker.pkg.dev/$PROJECT_ID/flux/flux-electrique
  _GKE_CLUSTER: flux-electrique-dev
  _GKE_REGION: europe-west1
  _GKE_NAMESPACE: flux-dev
  _DEPLOYMENT: flux-electrique
  _ENV: development
steps:
  - id: npm-ci-lint-build
    name: gcr.io/cloud-builders/npm
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "🔧 Installing dependencies..."
        npm ci
        echo "✅ Linting code..."
        npm run lint
        echo "🏗️  Building Next.js app..."
        npm run build
  - id: docker-build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - -t
      - ${_IMAGE}:dev-$SHORT_SHA
      - -t
      - ${_IMAGE}:dev-latest
      - .
  - id: trivy-scan
    name: aquasec/trivy:0.52.2
    entrypoint: /bin/sh
    args:
      - -c
      - |
        echo "🔍 Scanning for vulnerabilities..."
        trivy image --exit-code 0 --severity MEDIUM,LOW --no-progress ${_IMAGE}:dev-$SHORT_SHA
        trivy image --exit-code 1 --severity CRITICAL,HIGH --no-progress ${_IMAGE}:dev-$SHORT_SHA
  - id: docker-push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_IMAGE}
  - id: kubectl-apply
    name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}
      - CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        echo "🚀 Deploying to ${_ENV} environment..."
        kubectl apply -k k8s/overlays/dev/
        kubectl set image deployment/${_DEPLOYMENT} web=${_IMAGE}:dev-$SHORT_SHA -n ${_GKE_NAMESPACE}
        kubectl rollout status deployment/${_DEPLOYMENT} -n ${_GKE_NAMESPACE} --timeout=180s
        echo "✅ Deployment complete!"
images:
  - ${_IMAGE}:dev-$SHORT_SHA
  - ${_IMAGE}:dev-latest
